### ISSUE TITLE
Unrecognized ISO 8601 date format

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/rdf-prettifier#35]
Fra error-reporting, fdk-dataset-diff-store genererer ganske mange av disse

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/isodate/isodates.py", line 203, in parse_date
    raise ISO8601Error('Unrecognised ISO 8601 date format: %r' % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: ''
```

**Comment by valosnah** [comment]
Denne er fortsatt feil.
Loggen ser ikke ut til å inneholde noe særlig info om hvilken data-input/kilde som trigget feilen.
Jobben der denne feilen oppstår ser ikke ut til å kjøres helt tidsmessig konsekvent, men typisk 19-23.
Da logges det som regel mellom 3-10 feil samtidig.
![image](https://user-images.githubusercontent.com/8625716/233001050-00a58d13-1462-4a29-acab-0498f3506ca6.png)

**Comment by valosnah** [comment]
Arkiverer repo, lukkes
